name: aleef
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.1
  flutter_verification_code: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/on_boarding/


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirArabic-Medium.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

